
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class DAVID_COEN1202_FLExam extends javax.swing.JFrame {

    /**
     * Creates new form DAVID_COEN1202_FLExam
     */
    public DAVID_COEN1202_FLExam() {
        initComponents();
        jbtnConvert.setEnabled(false);
        jbtnAddToList.setEnabled(false);
        jbtnReset.setEnabled(false);
        jbtnExit.setEnabled(true);
        
    }
    public String toAnyNumberSystems(int num, int base){
        StringBuilder sb = new StringBuilder();
        String NumberSystemCode = "0123456789ABCDEF";
        String binNumber = "";
        int binDigit;
        
        if (num > 0){
            binNumber = toAnyNumberSystems(num/base, base);
            binDigit = num % base;
            sb.append(binNumber + NumberSystemCode.charAt(binDigit));
        }
        return sb.toString();
    }
    DefaultListModel model = new DefaultListModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlMain = new javax.swing.JPanel();
        jlblDec = new javax.swing.JLabel();
        jlblBase = new javax.swing.JLabel();
        jlblEqui = new javax.swing.JLabel();
        jtxtDec = new javax.swing.JTextField();
        jcmbBase = new javax.swing.JComboBox<>();
        jlblEquiv = new javax.swing.JLabel();
        jtxtRes = new javax.swing.JTextField();
        jbtnConvert = new javax.swing.JButton();
        jbtnAddToList = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListConverted = new javax.swing.JList<>();
        jlblDes = new javax.swing.JLabel();
        jpnlPROG = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Decimal To Any Number Converter UI");

        jPnlMain.setBackground(new java.awt.Color(0, 0, 0));
        jPnlMain.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DECIMAL TO ANY NUMBER CONVERTER", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        jPnlMain.setForeground(new java.awt.Color(255, 0, 51));

        jlblDec.setBackground(new java.awt.Color(0, 0, 0));
        jlblDec.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblDec.setForeground(new java.awt.Color(255, 255, 255));
        jlblDec.setText("DECIMAL NUMBER:");

        jlblBase.setBackground(new java.awt.Color(204, 204, 204));
        jlblBase.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblBase.setForeground(new java.awt.Color(255, 255, 255));
        jlblBase.setText("SELECT BASE NUMBER:");

        jlblEqui.setBackground(new java.awt.Color(204, 204, 204));
        jlblEqui.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblEqui.setForeground(new java.awt.Color(255, 255, 255));
        jlblEqui.setText("EQUIVALENT");

        jtxtDec.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtxtDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDecActionPerformed(evt);
            }
        });

        jcmbBase.setMaximumRowCount(20);
        jcmbBase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));
        jcmbBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbBaseActionPerformed(evt);
            }
        });

        jlblEquiv.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlblEquiv.setForeground(new java.awt.Color(255, 255, 255));

        jtxtRes.setEditable(false);
        jtxtRes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtxtRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtResActionPerformed(evt);
            }
        });

        jbtnConvert.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtnConvert.setText("CONVERT");
        jbtnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConvertActionPerformed(evt);
            }
        });

        jbtnAddToList.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtnAddToList.setText("ADD TO LIST");
        jbtnAddToList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddToListActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtnReset.setText("RESET");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtnExit.setText("EXIT");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jListConverted.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List Of Converted Outputs", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 3, 14))); // NOI18N
        jListConverted.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jListConverted);

        jlblDes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlblDes.setForeground(new java.awt.Color(255, 51, 0));
        jlblDes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblDes.setText("-----");

        jpnlPROG.setBackground(new java.awt.Color(0, 0, 0));
        jpnlPROG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jpnlPROG.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" PROGRAMMED BY:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Raven David, CpE1");

        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DECIMAL TO");

        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ANY NUMBER ");

        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SYSTEMS");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("            -----");

        javax.swing.GroupLayout jpnlPROGLayout = new javax.swing.GroupLayout(jpnlPROG);
        jpnlPROG.setLayout(jpnlPROGLayout);
        jpnlPROGLayout.setHorizontalGroup(
            jpnlPROGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jpnlPROGLayout.setVerticalGroup(
            jpnlPROGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPROGLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPnlMainLayout = new javax.swing.GroupLayout(jPnlMain);
        jPnlMain.setLayout(jPnlMainLayout);
        jPnlMainLayout.setHorizontalGroup(
            jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblDes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPnlMainLayout.createSequentialGroup()
                        .addGroup(jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlMainLayout.createSequentialGroup()
                                .addComponent(jlblEqui)
                                .addGap(18, 18, 18)
                                .addComponent(jlblEquiv, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtRes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPnlMainLayout.createSequentialGroup()
                                    .addComponent(jlblDec)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxtDec))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPnlMainLayout.createSequentialGroup()
                                    .addComponent(jlblBase)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jcmbBase, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnlPROG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPnlMainLayout.createSequentialGroup()
                        .addComponent(jbtnConvert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnAddToList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPnlMainLayout.setVerticalGroup(
            jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMainLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPnlMainLayout.createSequentialGroup()
                        .addGroup(jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblDec, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblBase)
                            .addComponent(jcmbBase, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblEquiv, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblEqui, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtRes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jpnlPROG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jlblDes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnConvert)
                    .addComponent(jbtnAddToList)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        JOptionPane.showMessageDialog(null, "FINALS OUTPUT OF: Raven David.", "Programmers Info", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtDec.setText("");
        jcmbBase.setSelectedIndex(0);
        jtxtRes.setText("");
        jlblEquiv.setText("");
        model.removeAllElements();
        jtxtDec.requestFocus();
        jbtnConvert.setEnabled(false);
        jbtnAddToList.setEnabled(false);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnAddToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddToListActionPerformed
        jListConverted.setModel(model);
        model.addElement("DECIMAL " + jtxtDec.getText() + " IS " + jlblEquiv.getText() + " IN BASE " + jtxtRes.getText());
        jbtnConvert.setEnabled(true);
        jbtnAddToList.setEnabled(false);
        jtxtDec.setText("");
        jcmbBase.setSelectedItem("2");
        jlblEquiv.setText("");
        jtxtDec.requestFocus();
        jtxtRes.setText("");

    }//GEN-LAST:event_jbtnAddToListActionPerformed

    private void jbtnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConvertActionPerformed
      
        if(jtxtDec.getText().isEmpty() == true){
            jbtnConvert.setEnabled(false);
            jbtnAddToList.setEnabled(false);
            jbtnReset.setEnabled(false);
            JOptionPane.showMessageDialog(null, "You Must Enter A Number", "Decimal Converter", JOptionPane.INFORMATION_MESSAGE);
        }else{
            jbtnConvert.setEnabled(true);
            jbtnAddToList.setEnabled(true);
            jbtnReset.setEnabled(true);
            int Decimal = Integer.parseInt(jtxtDec.getText());
            jtxtDec.setText(String.valueOf(Decimal));
        }

        if(jtxtDec.getText().isEmpty() == false){
            int Decimal = Integer.parseInt(jtxtDec.getText());
            if(Decimal < 0){
                JOptionPane.showMessageDialog(null, "Enter A Non Negative Integer.", "Decimal Converter", JOptionPane.INFORMATION_MESSAGE);
            }else{
                jtxtDec.setText(String.valueOf(Decimal));
                jbtnConvert.setEnabled(true);
                jbtnAddToList.setEnabled(true);
                jbtnReset.setEnabled(true);
            }
        }else {
            int Decimal = Integer.parseInt(jtxtDec.getText());
            jtxtDec.setText(String.valueOf(Decimal));
            jbtnConvert.setEnabled(false);
            jbtnAddToList.setEnabled(false);
            jbtnReset.setEnabled(false);
        }
        int Decimal = Integer.parseInt(jtxtDec.getText());
        String Number = jcmbBase.getSelectedItem().toString();
        int Num = Integer.parseInt(Number);
        jlblEquiv.setText(toAnyNumberSystems(Decimal,Num));
        jbtnConvert.setEnabled(false);
        jbtnAddToList.setEnabled(true);
    }//GEN-LAST:event_jbtnConvertActionPerformed

    private void jtxtResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtResActionPerformed

    private void jcmbBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbBaseActionPerformed
        String Base = jcmbBase.getSelectedItem().toString();
        jtxtRes.setText(Base);
        jbtnConvert.setEnabled(true);
        jbtnAddToList.setEnabled(true);
        jbtnReset.setEnabled(true);
    }//GEN-LAST:event_jcmbBaseActionPerformed

    private void jtxtDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDecActionPerformed
        if(jtxtDec.getText().isEmpty() == true){
            jbtnConvert.setEnabled(false);
            jbtnAddToList.setEnabled(false);
            jbtnReset.setEnabled(false);
            JOptionPane.showMessageDialog(null, "You Must Enter A Number", "Decimal Converter", JOptionPane.INFORMATION_MESSAGE);
        }else{
            jbtnConvert.setEnabled(true);
            jbtnAddToList.setEnabled(true);
            jbtnReset.setEnabled(true);
            int Decimal = Integer.parseInt(jtxtDec.getText());
            jtxtDec.setText(String.valueOf(Decimal));
        }

        if(jtxtDec.getText().isEmpty() == false){
            int Decimal = Integer.parseInt(jtxtDec.getText());
            if(Decimal < 0){
                JOptionPane.showMessageDialog(null, "Enter A Non Negative Integer.", "Decimal Converter", JOptionPane.INFORMATION_MESSAGE);
            }else{
                jtxtDec.setText(String.valueOf(Decimal));
                jbtnConvert.setEnabled(true);
                jbtnAddToList.setEnabled(true);
                jbtnReset.setEnabled(true);
            }
        }else {
            int Decimal = Integer.parseInt(jtxtDec.getText());
            jtxtDec.setText(String.valueOf(Decimal));
            jbtnConvert.setEnabled(false);
            jbtnAddToList.setEnabled(false);
            jbtnReset.setEnabled(false);
        }
    }//GEN-LAST:event_jtxtDecActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DAVID_COEN1202_FLExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DAVID_COEN1202_FLExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DAVID_COEN1202_FLExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DAVID_COEN1202_FLExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DAVID_COEN1202_FLExam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jListConverted;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPnlMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAddToList;
    private javax.swing.JButton jbtnConvert;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JComboBox<String> jcmbBase;
    private javax.swing.JLabel jlblBase;
    private javax.swing.JLabel jlblDec;
    private javax.swing.JLabel jlblDes;
    private javax.swing.JLabel jlblEqui;
    private javax.swing.JLabel jlblEquiv;
    private javax.swing.JPanel jpnlPROG;
    private javax.swing.JTextField jtxtDec;
    private javax.swing.JTextField jtxtRes;
    // End of variables declaration//GEN-END:variables
}
